### ISSUE TITLE
Page refresh sometimes needed

### ISSUE THREAD

**Issue by danielstockton** [danielstockton/stealth-youtube#3]
When clicking on links to related videos, the script doesn't always hide all of the thumbnails.

**Comment by mihneasim** [comment]
The new css-class toggle on html top node invalidates this bug. Please close if indeed no more an issue for you.

**Comment by danielstockton** [comment]
Thumbnails weren't hidden at all, but it fixes the refresh issue. I added some new css cd0c136.
